#ifndef PARANOID_LINUX_DRIVER_VERSION_H
#define PARANOID_LINUX_DRIVER_VERSION_H

#define AGENT_VERSION "@AGENT_FULL_VERSION@"
#define AGENT_VERSION_SHORT "@AGENT_VERSION_MAJOR@.@AGENT_VERSION_MINOR@.@AGENT_VERSION_PATCH@"
#define AGENT_VERSION_HASH "@AGENT_VERSION_HASH@"

#endif //PARANOID_LINUX_DRIVER_VERSION_H
